server:
  port: 8082

spring:
  liquibase:
    change-log: classpath:db/master.xml

  datasource:
    url: jdbc:postgresql://localhost:5434/auth-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
