version: '3.8'
services:

  payment-db:
    image: postgres:15.1-alpine
    container_name: payment-db
    environment:
      - POSTGRES_DB=payment-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  user-db:
    image: postgres:15.1-alpine
    container_name: user-db
    environment:
      - POSTGRES_DB=user-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"




